#!/bin/sh
#
# This is an example script
#
#These commands set up the Grid Environment for your job:
#PBS -N XCORRELATOR
#PBS -l nodes=1:ppn=16:seriesGPU,walltime=24:00:00
#PBS -q GPUQ
#

# Change to the directory from which the job was submitted.  
cd $PBS_O_WORKDIR

# Print the date and time
echo "Script started at "$(date)

# Host name of the node we are executing on
echo ""
echo "Running on: $(hostname)"
echo "-----------------------------------------------------------------------"
/home/bhugo/ska-res/ska-ddc/output_correlator/output_correlator/build/output_correlator 6553600 /home/bhugo/ska-res/ska-ddc/pydecimated4096e4_to_25_over_4.dat /home/bhugo/ska-res/ska-ddc/GPUCODE_DDC/output.dump
